###################  项目启动端口  ###################
server:
  port: 8888
  context-path: /

spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
#  jetbrick:
#     template:
#        enabled: true
#        charset: UTF-8
#        content-type: text/html
#        import:
#          macros: /templates/admin/comm/macros.html
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/tale?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      filters: log4j,wall,mergeStat

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/com.td.truck/**/mapping/*.xml
  typeAliasesPackage: com.td.truck.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用